/**
 * Action Type
 */

 /**
  * Access Token (Async)
  */
export const GET_ACCESS_TOKEN_SUCCESS = 'GET_ACCESS_TOKEN_SUCCESS'
export const GET_ACCESS_TOKEN_FAILURE = 'GET_ACCESS_TOKEN_FAILURE'
export const GET_ACCESS_TOKEN_STARTED = 'GET_ACCESS_TOKEN_STARTED'